
// export const GET_ITEMS = 'GET_ITEMS';
// export const ITEMS_LOADING = 'ITEMS_LOADING';
// export const ADD_ITEM = "ADD_ITEM";
// export const DELETE_ITEM = "DELETE_ITEM";

// export const GET_MOUSE = 'GET_MOUSE';
// export const MOUSE_LOADING = 'MOUSE_LOADING';

// export const GET_MOUSEPAD = 'GET_MOUSEPAD';
// export const MOUSEPAD_LOADING = 'MOUSEPAD_LOADING';

// export const GET_KEYBOARD = 'GET_KEYBOARD';
// export const KEYBOARD_LOADING = 'KEYBOARD_LOADING';

// export const SIGNIN_USER = 'SIGNIN_USER';
// export const SIGNUP_USER = 'SIGNUP_USER';


// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// export const GET_ERRORS = 'GET_ERRORS';
// export const GET_EMAIL_ERRORS = 'GET_EMAIL_ERRORS';
// export const GET_PASSWORD_ERRORS = 'GET_PASSWORD_ERRORS';

export const GET_LOGINWITHNUMIO_ERROR = 'GET_LOGINWITHNUMIO_ERROR';
export const USER_LOGINWITHNUMIO = 'USER_LOGINWITHNUMIO';
export const USER_LOGINWITHMETAMASK = 'USER_LOGINWITHMETAMASK'
export const USER_SIGNUPWITHMETAMASK = 'USER_SIGNUPWITHMETAMASK'
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_DAOATTRIBUTES = 'UPDATE_DAOATTRIBUTES'
